export class ActionsEnums {
  static GET_USERS = 'GET_USERS';
  static GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
  static GET_USERS_ERROR = 'GET_USERS_ERROR';

  static ADD_USER = 'ADD_USER';
  static ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
  static ADD_USER_ERROR = 'ADD_USER_ERROR';

  static EDIT_USER = 'EDIT_USER';
  static EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
  static EDIT_USER_ERROR = 'EDIT_USER_ERROR';

  static DELETE_USER = 'DELETE_USER';
  static DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
  static DELETE_USER_ERROR = 'DELETE_USER_ERROR';
}
